**Importing the Packages**

In [ ]:
import numpy as np

In [ ]:
np.printoptions(
    suppress = True,
    linewidth = 100,
    precision = 2,
)

**Importing the Data**

In [ ]:
raw_data_np = np.genfromtxt("loan-data.csv",
                            delimiter = ';',
                            encoding='latin-1')
raw_data_np

array([[          nan,           nan,           nan, ...,           nan,
                  nan,           nan],
       [4.8010226e+07,           nan, 3.5000000e+04, ...,           nan,
                  nan, 9.4529600e+03],
       [5.7693261e+07,           nan, 3.0000000e+04, ...,           nan,
                  nan, 4.6797000e+03],
       ...,
       [5.0415990e+07,           nan, 1.0000000e+04, ...,           nan,
                  nan, 2.1856400e+03],
       [4.6154151e+07,           nan,           nan, ...,           nan,
                  nan, 3.1994000e+03],
       [6.6055249e+07,           nan, 1.0000000e+04, ...,           nan,
                  nan, 3.0190000e+02]])

Since the first row has null values, we can omit it

In [ ]:
raw_data_np = np.genfromtxt("loan-data.csv", delimiter = ';', encoding='latin-1', skip_header = True, autostrip = True)
np.set_printoptions(linewidth=np.inf)
raw_data_np

array([[4.8010226e+07,           nan, 3.5000000e+04, ...,           nan,           nan, 9.4529600e+03],
       [5.7693261e+07,           nan, 3.0000000e+04, ...,           nan,           nan, 4.6797000e+03],
       [5.9432726e+07,           nan, 1.5000000e+04, ...,           nan,           nan, 1.9698300e+03],
       ...,
       [5.0415990e+07,           nan, 1.0000000e+04, ...,           nan,           nan, 2.1856400e+03],
       [4.6154151e+07,           nan,           nan, ...,           nan,           nan, 3.1994000e+03],
       [6.6055249e+07,           nan, 1.0000000e+04, ...,           nan,           nan, 3.0190000e+02]])

**Checking for incomplete data**

In [ ]:
np.isnan(raw_data_np)

array([[False,  True, False, ...,  True,  True, False],
       [False,  True, False, ...,  True,  True, False],
       [False,  True, False, ...,  True,  True, False],
       ...,
       [False,  True, False, ...,  True,  True, False],
       [False,  True,  True, ...,  True,  True, False],
       [False,  True, False, ...,  True,  True, False]])

In [ ]:
np.isnan(raw_data_np).sum()

88005

Default datatype for genfromtxt() is float, so all string values will be considered empty and be filled using nan's.

In [ ]:
temporary_fill = np.nanmax(raw_data_np) + 1
temporary_mean = np.nanmean(raw_data_np, axis = 0)

<ipython-input-7-eeff3b704aa1>:2: RuntimeWarning: Mean of empty slice
  temporary_mean = np.nanmean(raw_data_np, axis = 0)


In [ ]:
temporary_mean

array([5.40158092e+07,            nan, 1.52734632e+04,            nan, 1.53110421e+04,            nan, 1.66172948e+01, 4.40922179e+02,            nan,            nan,            nan,            nan,            nan, 3.14385094e+03])

By above observation, we see there are total 8 columns which have text values.

In [ ]:
temporary_stats = np.array([np.nanmin(raw_data_np, axis = 0),
                           temporary_mean,
                           np.nanmax(raw_data_np, axis = 0)])

<ipython-input-9-f918bd68decf>:1: RuntimeWarning: All-NaN slice encountered
  temporary_stats = np.array([np.nanmin(raw_data_np, axis = 0),
<ipython-input-9-f918bd68decf>:3: RuntimeWarning: All-NaN slice encountered
  np.nanmax(raw_data_np, axis = 0)])


We are getting error since nanmin(), nanmax() consists of nan values. So since numpy only deals with numeric data, we should separate our data into 2 different arrays. First one contains the numeric values only and 2nd one contains all text data.

In [ ]:
temporary_stats

array([[3.73332000e+05,            nan, 1.00000000e+03,            nan, 1.00000000e+03,            nan, 6.00000000e+00, 3.14200000e+01,            nan,            nan,            nan,            nan,            nan, 0.00000000e+00],
       [5.40158092e+07,            nan, 1.52734632e+04,            nan, 1.53110421e+04,            nan, 1.66172948e+01, 4.40922179e+02,            nan,            nan,            nan,            nan,            nan, 3.14385094e+03],
       [6.86165190e+07,            nan, 3.50000000e+04,            nan, 3.50000000e+04,            nan, 2.89900000e+01, 1.37297000e+03,            nan,            nan,            nan,            nan,            nan, 4.19136200e+04]])

**Splitting the data - Numeric + Text**

First we need to get which columns contains text data and which ones have numeric. This information is acheived using temporary_mean

In [ ]:
temporary_mean

array([5.40158092e+07,            nan, 1.52734632e+04,            nan, 1.53110421e+04,            nan, 1.66172948e+01, 4.40922179e+02,            nan,            nan,            nan,            nan,            nan, 3.14385094e+03])

*   np.isnan(temporary_mean):
This part checks each element in the temporary_mean array to see if it's NaN. It returns a boolean array where True indicates that the element is NaN, and False otherwise.
*   np.argwhere(...):
This function finds the indices of the True values in the boolean array.
Essentially, it tells you where the NaN values are located in the temporary_mean array.



In [ ]:
columns_string = np.argwhere(np.isnan(temporary_mean))
columns_string

array([[ 1],
       [ 3],
       [ 5],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [ ]:
#  The variable which stores indexes should be one-dimensional, hence we add squeeze().
columns_string = np.argwhere(np.isnan(temporary_mean)).squeeze()
columns_string

array([ 1,  3,  5,  8,  9, 10, 11, 12])

In [ ]:
columns_numeric = np.argwhere(np.isnan(temporary_mean) == False).squeeze()
columns_numeric

array([ 0,  2,  4,  6,  7, 13])

**Reimporting Dataset**

In [ ]:
load_data_strings = np.genfromtxt("loan-data.csv",
                                  delimiter = ';',
                                  encoding ='latin-1',
                                  usecols = columns_string,
                                  dtype = str,
                                  skip_header = True)
load_data_strings

array([['May-15', 'Current', ' 36 months', ..., 'Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', ' 36 months', ..., 'Source Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', ' 36 months', ..., 'Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', ' 36 months', ..., 'Source Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', ' 36 months', ..., 'Source Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', ' 36 months', ..., '', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']], dtype='<U69')

In [ ]:
load_data_numeric = np.genfromtxt("loan-data.csv",
                                  delimiter = ';',
                                  encoding ='latin-1',
                                  usecols = columns_numeric,
                                  filling_values = temporary_fill
                                  )
load_data_numeric

array([[6.8616520e+07, 6.8616520e+07, 6.8616520e+07, 6.8616520e+07, 6.8616520e+07, 6.8616520e+07],
       [4.8010226e+07, 3.5000000e+04, 3.5000000e+04, 1.3330000e+01, 1.1848600e+03, 9.4529600e+03],
       [5.7693261e+07, 3.0000000e+04, 3.0000000e+04, 6.8616520e+07, 9.3857000e+02, 4.6797000e+03],
       ...,
       [5.0415990e+07, 1.0000000e+04, 1.0000000e+04, 6.8616520e+07, 6.8616520e+07, 2.1856400e+03],
       [4.6154151e+07, 6.8616520e+07, 1.0000000e+04, 1.6550000e+01, 3.5430000e+02, 3.1994000e+03],
       [6.6055249e+07, 1.0000000e+04, 1.0000000e+04, 6.8616520e+07, 3.0997000e+02, 3.0190000e+02]])

**The Names of the Columns**


In [ ]:
# We will skip all rows in data using skip_footer, defined as number of rows
# in raw_data_np
header_full = np.genfromtxt("loan-data.csv",
                                  delimiter = ';',
                                  encoding ='latin-1',
                                  #skip_footer = raw_data_np.shape[0],
                                  max_rows = 1,
                                  dtype = str
                                  )
header_full

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate', 'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state', 'total_pymnt'], dtype='<U19')

In [ ]:
header_strings, header_numeric = header_full[columns_string], header_full[columns_numeric]

In [ ]:
header_strings

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state'], dtype='<U19')

In [ ]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

**Creating Checkpoint**
Is where we store a copy of our dataset or only parts of it.


In [ ]:
def checkpoint(file_name, checkpoint_header, checkpoint_data):
  np.savez(file_name, header = checkpoint_header, data = checkpoint_data) # Fixed the typo here
  checkpoint_variable = np.load(file_name + ".npz")
  return(checkpoint_variable)

In [ ]:
checkpoint_test = checkpoint("checkpoint_test", header_strings, load_data_strings)
checkpoint_test['header']

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state'], dtype='<U19')

In [ ]:
checkpoint_test['data']

array([['May-15', 'Current', ' 36 months', ..., 'Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', ' 36 months', ..., 'Source Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', ' 36 months', ..., 'Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', ' 36 months', ..., 'Source Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', ' 36 months', ..., 'Source Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', ' 36 months', ..., '', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']], dtype='<U69')

**MANIPULATING STRING COLUMNS**
   [load_data_string]

In [ ]:
header_strings

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state'], dtype='<U19')

In [ ]:
# As column names are not clear we redefine them as per our convenience.
header_strings[0] = "issue_date"

In [ ]:
load_data_strings

array([['May-15', 'Current', ' 36 months', ..., 'Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', ' 36 months', ..., 'Source Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', ' 36 months', ..., 'Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', ' 36 months', ..., 'Source Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', ' 36 months', ..., 'Source Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', ' 36 months', ..., '', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']], dtype='<U69')

**Issue Date**

In [ ]:
# Displaying first column
load_data_strings[:,0]

array(['May-15', '', 'Sep-15', ..., 'Jun-15', 'Apr-15', 'Dec-15'], dtype='<U69')

In [ ]:
np.unique(load_data_strings[:,0])

array(['', 'Apr-15', 'Aug-15', 'Dec-15', 'Feb-15', 'Jan-15', 'Jul-15', 'Jun-15', 'Mar-15', 'May-15', 'Nov-15', 'Oct-15', 'Sep-15'], dtype='<U69')

In [ ]:
# We see all loans are from year 2015, so we can remove it. Store data in column
load_data_strings[:,0] = np.chararray.strip(load_data_strings[:,0],"-15")

In [ ]:
np.unique(load_data_strings[:,0])

array(['', 'Apr', 'Aug', 'Dec', 'Feb', 'Jan', 'Jul', 'Jun', 'Mar', 'May', 'Nov', 'Oct', 'Sep'], dtype='<U69')

In [ ]:
# Change each month to numeric
months = np.array(['', 'Jan', 'Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'])

In [ ]:
# np.where(condition, value_if_true, value_if_false)
for i in range(13):
  load_data_strings[:,0] = np.where(load_data_strings[:,0] == months[i],
                                    i,
                                    load_data_strings[:,0])



In [ ]:
np.unique(load_data_strings[:,0])

array(['0', '1', '10', '11', '12', '2', '3', '4', '5', '6', '7', '8', '9'], dtype='<U69')

**Loan Status**

In [ ]:
header_strings

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state'], dtype='<U19')

In [ ]:
np.unique(load_data_strings[:,1])

array(['', 'Charged Off', 'Current', 'Default', 'Fully Paid', 'In Grace Period', 'Issued', 'Late (16-30 days)', 'Late (31-120 days)'], dtype='<U69')

In [ ]:
np.unique(load_data_strings[:,1]).size

9

In [ ]:
# Here also we can use where function to make values in numeric, but what we require here is if person is in good financial condition or not.
# So we need to split values in 2 groups [Good {Current, In grace period, Issued, Fully Paid, Late (16-30 days)}, bad].
# If no data is provided, we treat as bad sign.
# For good - We will use 1, for bad - 0.

In [ ]:
status_bad = np.array(['', 'Charged Off', 'Default', 'Late (31-120 days)'])

In [ ]:
load_data_strings[:,1] = np.where(np.isin(load_data_strings[:,1], status_bad), 0, 1)

In [ ]:
np.unique(load_data_strings[:,1])

array(['0', '1'], dtype='<U69')

**Term**

In [ ]:
header_strings

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state'], dtype='<U19')

In [ ]:
np.unique(load_data_strings[:,2])

array(['', ' 36 months', ' 60 months'], dtype='<U69')

In [ ]:
load_data_strings[:,2] = np.chararray.strip(load_data_strings[:,2],' months')
np.unique(load_data_strings[:,2])

array(['', '36', '60'], dtype='<U69')

In [ ]:
header_strings[2] = "term_months"

In [ ]:
# We should assume worst case and assign 60 to empty values [since 60 months = 5 yrs]
# Assin 60 to all empty places.
load_data_strings[:,2] = np.where(load_data_strings[:,2] == '', 60, load_data_strings[:,2])

In [ ]:
np.unique(load_data_strings[:,2])

array(['36', '60'], dtype='<U69')

**Grade and Subgrade**

In [ ]:
header_strings

array(['issue_date', 'loan_status', 'term_months', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state'], dtype='<U19')

In [ ]:
load_data_strings[:,3]

array(['C', 'A', 'B', ..., 'A', 'D', 'A'], dtype='<U69')

In [ ]:
np.unique(load_data_strings[:,3])

array(['', 'A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69')

In [ ]:
np.unique(load_data_strings[:,4])

array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69')

**Filling SubGrade**

In [ ]:
 # If Grade has value B and subgrade is empty, we replace subgarde with B5 [Worst Case]

In [ ]:
# We start after first because first is '', empty space. Hence[:,3][1:]
for i in np.unique(load_data_strings[:,3])[1:]:
  load_data_strings[:,4] = np.where((load_data_strings[:,4] == '') & (load_data_strings[:,3] == i),i + '5',load_data_strings[:,4])

In [ ]:
np.unique(load_data_strings[:,4])

array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69')

In [ ]:
load_data_strings[:,4] = np.where(load_data_strings[:,4] == '', 'H1', load_data_strings[:,4])

In [ ]:
np.unique(load_data_strings[:,4])

array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5', 'G1', 'G2', 'G3', 'G4', 'G5', 'H1'], dtype='<U69')

In [ ]:
# We dont have any use of Grade column now, All information is present in subgrade column.
load_data_strings = np.delete(load_data_strings, 3, axis = 1)

In [ ]:
load_data_strings

array([['5', '1', '36', ..., 'Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['0', '1', '36', ..., 'Source Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['9', '1', '36', ..., 'Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['6', '1', '36', ..., 'Source Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['4', '1', '36', ..., 'Source Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['12', '1', '36', ..., '', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']], dtype='<U69')

In [ ]:
header_strings

array(['issue_date', 'loan_status', 'term_months', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state'], dtype='<U19')

In [ ]:
header_strings = np.delete(header_strings,3)

In [ ]:
header_strings

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'url', 'addr_state'], dtype='<U19')

**Converting Sub_Grade**

In [ ]:
np.unique(load_data_strings[:,3])

array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5', 'G1', 'G2', 'G3', 'G4', 'G5', 'H1'], dtype='<U69')

In [ ]:
# Converting sub_grades into an dictionary. So we can assign numeric values.
keys = list(np.unique(load_data_strings[:,3]))
values = list(range(1, np.unique(load_data_strings[:,3]).shape[0] + 1))
dict_sub_grade = dict(zip(keys, values))

In [ ]:
dict_sub_grade

{'A1': 1,
 'A2': 2,
 'A3': 3,
 'A4': 4,
 'A5': 5,
 'B1': 6,
 'B2': 7,
 'B3': 8,
 'B4': 9,
 'B5': 10,
 'C1': 11,
 'C2': 12,
 'C3': 13,
 'C4': 14,
 'C5': 15,
 'D1': 16,
 'D2': 17,
 'D3': 18,
 'D4': 19,
 'D5': 20,
 'E1': 21,
 'E2': 22,
 'E3': 23,
 'E4': 24,
 'E5': 25,
 'F1': 26,
 'F2': 27,
 'F3': 28,
 'F4': 29,
 'F5': 30,
 'G1': 31,
 'G2': 32,
 'G3': 33,
 'G4': 34,
 'G5': 35,
 'H1': 36}

In [ ]:
# Pass numeric value to load_data_strings, instead of A1, A2..
for i in np.unique(load_data_strings[:,3]):
  load_data_strings[:,3] = np.where((load_data_strings[:,3] == i), dict_sub_grade[i], load_data_strings[:,3])

In [ ]:
np.unique(load_data_strings[:,3])

array(['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '3', '30', '31', '32', '33', '34', '35', '36', '4', '5', '6', '7', '8', '9'], dtype='<U69')

**Verification Status**

In [ ]:
header_strings

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'url', 'addr_state'], dtype='<U19')

In [ ]:
np.unique(load_data_strings[:,4])

array(['', 'Not Verified', 'Source Verified', 'Verified'], dtype='<U69')

In [ ]:
# Assuming empty string ~~ to Not Verified.
# Make 2 Groups - {'',Not Verified} and {SOurce Verified, Verified}
load_data_strings[:,4] = np.where((load_data_strings[:,4] == '') | (load_data_strings[:,4] == 'Not Verified'), 0, 1)

In [ ]:
np.unique(load_data_strings[:,4])

array(['0', '1'], dtype='<U69')

**URL**

In [ ]:
np.unique(load_data_strings[:,5])

array(['https://www.lendingclub.com/browse/loanDetail.action?loan_id=12606806', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=13026045', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=1312426', ..., 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=8138291', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=8214572', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=849994'], dtype='<U69')

In [ ]:
# ONly keep ID part, remove repeating part using strip
load_data_strings[:,5] = np.chararray.strip(load_data_strings[:,5],'https://www.lendingclub.com/browse/loanDetail.action?loan_id=')
load_data_strings[:,5]

array(['48010226', '57693261', '59432726', ..., '50415990', '46154151', '66055249'], dtype='<U69')

In [ ]:
header_full

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate', 'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state', 'total_pymnt'], dtype='<U19')

In [ ]:
# Convert data to numeric and compare if id and url value are same or not.
load_data_numeric[:,0].astype(dtype = int)

array([68616520, 48010226, 57693261, ..., 50415990, 46154151, 66055249])

In [ ]:
load_data_strings[:,5].astype(dtype = int)

array([48010226, 57693261, 59432726, ..., 50415990, 46154151, 66055249])

In [ ]:
load_data_numeric[:,0].astype(dtype = int).shape[0]

10001

In [ ]:
load_data_strings[:,5].shape[0]

10000

In [ ]:
index = np.where(load_data_numeric == 68616520)[0][0]
index

0

In [ ]:
load_data_numeric = np.delete(load_data_numeric, 0, axis=0)
load_data_numeric.shape

(10000, 6)

In [ ]:
np.array_equal(load_data_numeric[:,0].astype(dtype = np.int32), load_data_strings[:,5].astype(dtype = np.int32))

True

In [ ]:
# Since both id and URL columns are same, we can remove url column.
load_data_strings = np.delete(load_data_strings, 5, axis = 1)
header_strings = np.delete(header_strings, 5)

In [ ]:
header_strings

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'addr_state'], dtype='<U19')

In [ ]:
load_data_strings[:,5]

array(['CA', 'NY', 'PA', ..., 'CA', 'OH', 'IL'], dtype='<U69')

In [ ]:
header_strings

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'addr_state'], dtype='<U19')

**verification_status**

In [ ]:
np.unique(load_data_strings[:,4])

array(['0', '1'], dtype='<U69')

***State Address***

In [ ]:
np.unique(load_data_strings[:,5])

array(['', 'AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IL', 'IN', 'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH', 'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA', 'VT', 'WA', 'WI', 'WV', 'WY'], dtype='<U69')

In [ ]:
states_names, states_count = np.unique(load_data_strings[:,5], return_counts = True)

In [ ]:
states_count_sorted = np.argsort(-states_count)
states_names[states_count_sorted],states_count[states_count_sorted]

(array(['CA', 'NY', 'TX', 'FL', '', 'IL', 'NJ', 'GA', 'PA', 'OH', 'MI', 'NC', 'VA', 'MD', 'AZ', 'WA', 'MA', 'CO', 'MO', 'MN', 'IN', 'WI', 'CT', 'TN', 'NV', 'AL', 'LA', 'OR', 'SC', 'KY', 'KS', 'OK', 'UT', 'AR', 'MS', 'NH', 'NM', 'WV', 'HI', 'RI', 'MT', 'DE', 'DC', 'WY', 'AK', 'NE', 'SD', 'VT', 'ND', 'ME'], dtype='<U69'),
 array([1336,  777,  758,  690,  500,  389,  341,  321,  320,  312,  267,  261,  242,  222,  220,  216,  210,  201,  160,  156,  152,  148,  143,  143,  130,  119,  116,  108,  107,   84,   84,   83,   74,   74,   61,   58,   57,   49,   44,   40,   28,   27,   27,   27,   26,   25,   24,   17,   16,   10]))

In [ ]:
# Pass 0 in empty spaces
load_data_strings[:,5] = np.where(load_data_strings[:,5] == '', 0, load_data_strings[:,5])

In [ ]:
# Divide states in 4 categories
states_west = np.array(['WA', 'OR','CA','NV','ID','MT', 'WY','UT','CO', 'AZ','NM','HI','AK'])
states_south = np.array(['TX','OK','AR','LA','MS','AL','TN','KY','FL','GA','SC','WV','VA','MD','DE','NC','RI','SC','DC'])
states_midwest = np.array(['ND','SD','NE','KS','MN','IA','MO','WI','IL','IN','MI','OH'])
states_east = np.array(['PA','NY','NJ','CT','MA','VT','NH','ME','RI'])

In [ ]:
load_data_strings[:,5] = np.where(np.isin(load_data_strings[:,5],states_west), 1, load_data_strings[:,5])
load_data_strings[:,5] = np.where(np.isin(load_data_strings[:,5],states_south), 2, load_data_strings[:,5])
load_data_strings[:,5] = np.where(np.isin(load_data_strings[:,5],states_midwest), 3, load_data_strings[:,5])
load_data_strings[:,5] = np.where(np.isin(load_data_strings[:,5],states_east), 4, load_data_strings[:,5])

In [ ]:
np.unique(load_data_strings[:,5])


array(['0', '1', '2', '3', '4'], dtype='<U69')

**Converting to Numbers**

In [ ]:
load_data_strings

array([['5', '1', '36', '13', '1', '1'],
       ['0', '1', '36', '5', '1', '4'],
       ['9', '1', '36', '10', '1', '4'],
       ...,
       ['6', '1', '36', '5', '1', '1'],
       ['4', '1', '36', '17', '1', '3'],
       ['12', '1', '36', '4', '0', '3']], dtype='<U69')

In [ ]:
# Since all values are string convert to numbers
load_data_strings = load_data_strings.astype(dtype = int)
load_data_strings

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

**Creating checkpoint1:**

In [ ]:
checkpoint_strings = checkpoint("checkpoint_strings", header_strings, load_data_strings)
checkpoint_strings['header']

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'addr_state'], dtype='<U19')

In [ ]:
checkpoint_strings['data']

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

In [ ]:
np.array_equal(load_data_strings, checkpoint_strings['data'])

True

**MANIPULATING NUMERIC COLUMNS:** [load_data_numeric]

In [ ]:
load_data_numeric

array([[4.8010226e+07, 3.5000000e+04, 3.5000000e+04, 1.3330000e+01, 1.1848600e+03, 9.4529600e+03],
       [5.7693261e+07, 3.0000000e+04, 3.0000000e+04, 6.8616520e+07, 9.3857000e+02, 4.6797000e+03],
       [5.9432726e+07, 1.5000000e+04, 1.5000000e+04, 6.8616520e+07, 4.9486000e+02, 1.9698300e+03],
       ...,
       [5.0415990e+07, 1.0000000e+04, 1.0000000e+04, 6.8616520e+07, 6.8616520e+07, 2.1856400e+03],
       [4.6154151e+07, 6.8616520e+07, 1.0000000e+04, 1.6550000e+01, 3.5430000e+02, 3.1994000e+03],
       [6.6055249e+07, 1.0000000e+04, 1.0000000e+04, 6.8616520e+07, 3.0997000e+02, 3.0190000e+02]])

In [ ]:
# 0 specifies theres no missing data here.
np.isnan(load_data_numeric).sum()

0

In [ ]:
# But when we created load_numeric_data array, we have filled all missing values using temporary_fill


**Substitute Filler Values**

In [ ]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

**ID**

In [ ]:
# id should never be missing
np.isnan(load_data_numeric[:,0]).sum()

0

In [ ]:
temporary_fill

68616520.0

In [ ]:
np.isin(load_data_numeric[:,0], temporary_fill)

array([False, False, False, ..., False, False, False])

In [ ]:
np.isin(load_data_numeric[:,0], temporary_fill).sum()

0

In [ ]:
# This means we have not filled any missing values for column ID.

In [ ]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [ ]:
# Considering Worst case: loan_amnt, int_rate, installement, total_pymnt all missing values will have max value as replacement .
# Funded_amnt will have min value as replacemnet for missing values.
# We created temporary_stats, which contans min, max and mean values.

In [ ]:
temporary_stats
# This contains many NaN values, These Nan are from string columns.
# We defined column_strings, column_numerics.

array([[3.73332000e+05,            nan, 1.00000000e+03,            nan, 1.00000000e+03,            nan, 6.00000000e+00, 3.14200000e+01,            nan,            nan,            nan,            nan,            nan, 0.00000000e+00],
       [5.40158092e+07,            nan, 1.52734632e+04,            nan, 1.53110421e+04,            nan, 1.66172948e+01, 4.40922179e+02,            nan,            nan,            nan,            nan,            nan, 3.14385094e+03],
       [6.86165190e+07,            nan, 3.50000000e+04,            nan, 3.50000000e+04,            nan, 2.89900000e+01, 1.37297000e+03,            nan,            nan,            nan,            nan,            nan, 4.19136200e+04]])

In [ ]:
columns_numeric

array([ 0,  2,  4,  6,  7, 13])

In [ ]:
# So to  display only min, mean, max of numeric columns:
temporary_stats[:,columns_numeric]

array([[3.73332000e+05, 1.00000000e+03, 1.00000000e+03, 6.00000000e+00, 3.14200000e+01, 0.00000000e+00],
       [5.40158092e+07, 1.52734632e+04, 1.53110421e+04, 1.66172948e+01, 4.40922179e+02, 3.14385094e+03],
       [6.86165190e+07, 3.50000000e+04, 3.50000000e+04, 2.89900000e+01, 1.37297000e+03, 4.19136200e+04]])

In [ ]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

**Funded Amount** [Missing values = min of that col]

In [ ]:
load_data_numeric[:,2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.])

In [ ]:
np.isin(load_data_numeric[:,2], temporary_fill)

array([False, False, False, ..., False, False, False])

In [ ]:
np.isin(load_data_numeric[:,2], temporary_fill).sum()

500

In [ ]:
# Missing values have been replaced by temporary_fill
# Now replace them with min value in col from temporary_stats
load_data_numeric[:,2] = np.where(load_data_numeric[:,2] == temporary_fill, temporary_stats[0, columns_numeric[2]], load_data_numeric[:,2]) # Removed load_data_numeric[:,2] from the index as it is an array of floats
load_data_numeric[:,2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.])

**Loaned Amount, Intrest rate, Total Paymnet, Installment**

In [ ]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [ ]:
for i in [1,3,4,5]:
  load_data_numeric[:,i] = np.where(load_data_numeric[:,i] == temporary_fill, temporary_stats[2, columns_numeric[i]], load_data_numeric[:,i])

In [ ]:
load_data_numeric

array([[4.8010226e+07, 3.5000000e+04, 3.5000000e+04, 1.3330000e+01, 1.1848600e+03, 9.4529600e+03],
       [5.7693261e+07, 3.0000000e+04, 3.0000000e+04, 2.8990000e+01, 9.3857000e+02, 4.6797000e+03],
       [5.9432726e+07, 1.5000000e+04, 1.5000000e+04, 2.8990000e+01, 4.9486000e+02, 1.9698300e+03],
       ...,
       [5.0415990e+07, 1.0000000e+04, 1.0000000e+04, 2.8990000e+01, 1.3729700e+03, 2.1856400e+03],
       [4.6154151e+07, 3.5000000e+04, 1.0000000e+04, 1.6550000e+01, 3.5430000e+02, 3.1994000e+03],
       [6.6055249e+07, 1.0000000e+04, 1.0000000e+04, 2.8990000e+01, 3.0997000e+02, 3.0190000e+02]])

**Currency Rate**

In [ ]:
# Now that all missing data is handled we need to Convert all currency in Euros from Dollars.

***The Exchange Rate ***

In [ ]:
# EUR_USD.csv contains average monthly exchange rates for year 2015.
EUR_USD = np.genfromtxt('EUR-USD.csv', delimiter = ',', autostrip = True)
EUR_USD

array([[       nan,        nan,        nan,        nan,        nan],
       [1.20986283, 1.20986283, 1.11055589, 1.1287955 , 0.        ],
       [1.1287955 , 1.1484195 , 1.11768055, 1.12053609, 0.        ],
       [1.1197958 , 1.12404001, 1.04600322, 1.08302462, 0.        ],
       [1.07410228, 1.12475944, 1.05215979, 1.11143219, 0.        ],
       [1.12150371, 1.1453048 , 1.08219957, 1.09603453, 0.        ],
       [1.09590244, 1.14284015, 1.08889043, 1.12229669, 0.        ],
       [1.11349893, 1.1219995 , 1.08127046, 1.0939244 , 0.        ],
       [1.09690011, 1.1705997 , 1.08503056, 1.13400543, 0.        ],
       [1.12259901, 1.14600039, 1.10896957, 1.12559378, 0.        ],
       [1.11715615, 1.14942002, 1.09100032, 1.10089719, 0.        ],
       [1.10249937, 1.10600019, 1.05640018, 1.05830181, 0.        ],
       [1.05729473, 1.10700047, 1.05419958, 1.09339809, 0.        ]])

In [ ]:
# The first row having nan contain column names.
EUR_USD = np.genfromtxt('EUR-USD.csv', delimiter = ',', autostrip = True, dtype = str)
EUR_USD

array([['Open', 'High', 'Low', 'Close', 'Volume'],
       ['1.2098628282546997', '1.2098628282546997', '1.11055588722229', '1.1287955045700073', '0'],
       ['1.1287955045700073', '1.1484194993972778', '1.117680549621582', '1.1205360889434814', '0'],
       ['1.119795799255371', '1.1240400075912476', '1.0460032224655151', '1.0830246210098267', '0'],
       ['1.0741022825241089', '1.1247594356536865', '1.0521597862243652', '1.1114321947097778', '0'],
       ['1.1215037107467651', '1.145304799079895', '1.0821995735168457', '1.0960345268249512', '0'],
       ['1.095902442932129', '1.1428401470184326', '1.0888904333114624', '1.122296690940857', '0'],
       ['1.1134989261627197', '1.1219995021820068', '1.081270456314087', '1.0939244031906128', '0'],
       ['1.0969001054763794', '1.1705996990203857', '1.0850305557250977', '1.1340054273605347', '0'],
       ['1.1225990056991577', '1.1460003852844238', '1.1089695692062378', '1.1255937814712524', '0'],
       ['1.1171561479568481', '1.149420

In [ ]:
# We only want closing value for each day:
EUR_USD = np.genfromtxt('EUR-USD.csv', delimiter = ',', autostrip = True, skip_header = True, usecols = 3)
EUR_USD

array([1.1287955 , 1.12053609, 1.08302462, 1.11143219, 1.09603453, 1.12229669, 1.0939244 , 1.13400543, 1.12559378, 1.10089719, 1.05830181, 1.09339809])

In [ ]:
# This contain data about issue_date
load_data_strings[:,0]

array([ 5,  0,  9, ...,  6,  4, 12])

In [ ]:
exchange_rate = load_data_strings[:,0]
for i in range(1,13):
  exchange_rate = np.where(exchange_rate == i, EUR_USD[i-1], exchange_rate)

exchange_rate = np.where(exchange_rate == 0, np.mean(EUR_USD), exchange_rate)
exchange_rate

array([1.09603453, 1.10568669, 1.12559378, ..., 1.12229669, 1.11143219, 1.09339809])

In [ ]:
exchange_rate.shape

(10000,)

In [ ]:
load_data_numeric.shape

(10000, 6)

In [ ]:
# This will change shape from row vector to a column vector.
exchange_rate = np.reshape(exchange_rate, (10000,1))
exchange_rate.shape

(10000, 1)

In [ ]:
# Merging load_data_numeric and exchange_rate
load_data_numeric = np.hstack((load_data_numeric, exchange_rate))
load_data_numeric

array([[4.80102260e+07, 3.50000000e+04, 3.50000000e+04, ..., 1.18486000e+03, 9.45296000e+03, 1.09603453e+00],
       [5.76932610e+07, 3.00000000e+04, 3.00000000e+04, ..., 9.38570000e+02, 4.67970000e+03, 1.10568669e+00],
       [5.94327260e+07, 1.50000000e+04, 1.50000000e+04, ..., 4.94860000e+02, 1.96983000e+03, 1.12559378e+00],
       ...,
       [5.04159900e+07, 1.00000000e+04, 1.00000000e+04, ..., 1.37297000e+03, 2.18564000e+03, 1.12229669e+00],
       [4.61541510e+07, 3.50000000e+04, 1.00000000e+04, ..., 3.54300000e+02, 3.19940000e+03, 1.11143219e+00],
       [6.60552490e+07, 1.00000000e+04, 1.00000000e+04, ..., 3.09970000e+02, 3.01900000e+02, 1.09339809e+00]])

In [ ]:
# Since we added new column to load_data_numeric, we will add column in header also.
header_numeric = np.concatenate((header_numeric, np.array(['exchange_rate'])))
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate'], dtype='<U19')

**From USD to EURO**

In [ ]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate'], dtype='<U19')

In [ ]:
# We need to convert loan_amt, funded_amnt, installment, total_pymt columns to Euro's
column_dollars = np.array([1,2,4,5])
column_dollars

array([1, 2, 4, 5])

In [ ]:
# Exchange_rate is col 7
load_data_numeric[:,6]

array([1.09603453, 1.10568669, 1.12559378, ..., 1.12229669, 1.11143219, 1.09339809])

In [ ]:
for i in column_dollars:
  load_data_numeric = np.hstack((load_data_numeric, np.reshape(load_data_numeric[:,i] / load_data_numeric[:,6], (10000,1))))
load_data_numeric

array([[4.80102260e+07, 3.50000000e+04, 3.50000000e+04, ..., 3.19333006e+04, 1.08104259e+03, 8.62469180e+03],
       [5.76932610e+07, 3.00000000e+04, 3.00000000e+04, ..., 2.71324600e+04, 8.48857099e+02, 4.23239243e+03],
       [5.94327260e+07, 1.50000000e+04, 1.50000000e+04, ..., 1.33262996e+04, 4.39643509e+02, 1.75003632e+03],
       ...,
       [5.04159900e+07, 1.00000000e+04, 1.00000000e+04, ..., 8.91029982e+03, 1.22335743e+03, 1.94747077e+03],
       [4.61541510e+07, 3.50000000e+04, 1.00000000e+04, ..., 8.99739997e+03, 3.18777881e+02, 2.87862815e+03],
       [6.60552490e+07, 1.00000000e+04, 1.00000000e+04, ..., 9.14579974e+03, 2.83492354e+02, 2.76111694e+02]])

In [ ]:
load_data_numeric.shape

(10000, 11)

**Updating Header :** As columns have been updated in load_data_numeric

In [ ]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate'], dtype='<U19')

In [ ]:
column_dollars

array([1, 2, 4, 5])

In [ ]:
header_additional = np.array([column_name + '_EUR' for column_name in header_numeric[column_dollars]])
header_additional

array(['loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U15')

In [ ]:
header_numeric = np.concatenate((header_numeric, header_additional))
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate', 'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U19')

In [ ]:
column_dollars

array([1, 2, 4, 5])

In [ ]:
header_numeric[column_dollars] = np.array([column_name + '_USD' for column_name in header_numeric[column_dollars]])
header_numeric

array(['id', 'loan_amnt_USD', 'funded_amnt_USD', 'int_rate', 'installment_USD', 'total_pymnt_USD', 'exchange_rate', 'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U19')

In [ ]:
# Rearranging columns
column_index_order = [0,1,7,2,8,3,4,9,5,10,6]
header_numeric = header_numeric[column_index_order]
header_numeric

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate', 'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'], dtype='<U19')

In [ ]:
load_data_numeric = load_data_numeric[:,column_index_order]

In [ ]:
load_data_numeric.shape

(10000, 11)

**Interest Rate**

In [ ]:
header_numeric

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate', 'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'], dtype='<U19')

HERE

In [ ]:
load_data_numeric.shape

(10000, 11)

In [ ]:
load_data_numeric[:,5]

array([13.33, 28.99, 28.99, ..., 28.99, 16.55, 28.99])

In [ ]:
# Since values are very high, we can store them in between 0 - 1
load_data_numeric[:,5] = (load_data_numeric[:,5])/10000
load_data_numeric[:,5]

array([0.001333, 0.002899, 0.002899, ..., 0.002899, 0.001655, 0.002899])

In [ ]:
load_data_numeric.shape

(10000, 11)

**Checkpoint2: Numeric**

In [ ]:
checkpoint_numeric = checkpoint("checkpoint_numeric", header_numeric, load_data_numeric)
checkpoint_numeric['header'], checkpoint_numeric['data']

(array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate', 'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'], dtype='<U19'),
 array([[4.80102260e+07, 3.50000000e+04, 3.19333006e+04, ..., 9.45296000e+03, 8.62469180e+03, 1.09603453e+00],
        [5.76932610e+07, 3.00000000e+04, 2.71324600e+04, ..., 4.67970000e+03, 4.23239243e+03, 1.10568669e+00],
        [5.94327260e+07, 1.50000000e+04, 1.33262996e+04, ..., 1.96983000e+03, 1.75003632e+03, 1.12559378e+00],
        ...,
        [5.04159900e+07, 1.00000000e+04, 8.91029982e+03, ..., 2.18564000e+03, 1.94747077e+03, 1.12229669e+00],
        [4.61541510e+07, 3.50000000e+04, 3.14908999e+04, ..., 3.19940000e+03, 2.87862815e+03, 1.11143219e+00],
        [6.60552490e+07, 1.00000000e+04, 9.14579974e+03, ..., 3.01900000e+02, 2.76111694e+02, 1.09339809e+00]]))

**Creating the complete Dataset**

In [ ]:
# Here we will combine the Numeric and Strings data.
# Then sort it save its content to a csv file.

In [ ]:
checkpoint_strings['data'].shape

(10000, 6)

In [ ]:
checkpoint_numeric['data'].shape

(10000, 11)

In [ ]:
# Since both datasets have same rows, we can stack them side by side
np.hstack((checkpoint_numeric['data'], checkpoint_strings['data'])).shape

(10000, 17)

In [ ]:
loan_data = np.hstack((checkpoint_numeric['data'], checkpoint_strings['data']))
loan_data

array([[4.80102260e+07, 3.50000000e+04, 3.19333006e+04, ..., 1.30000000e+01, 1.00000000e+00, 1.00000000e+00],
       [5.76932610e+07, 3.00000000e+04, 2.71324600e+04, ..., 5.00000000e+00, 1.00000000e+00, 4.00000000e+00],
       [5.94327260e+07, 1.50000000e+04, 1.33262996e+04, ..., 1.00000000e+01, 1.00000000e+00, 4.00000000e+00],
       ...,
       [5.04159900e+07, 1.00000000e+04, 8.91029982e+03, ..., 5.00000000e+00, 1.00000000e+00, 1.00000000e+00],
       [4.61541510e+07, 3.50000000e+04, 3.14908999e+04, ..., 1.70000000e+01, 1.00000000e+00, 3.00000000e+00],
       [6.60552490e+07, 1.00000000e+04, 9.14579974e+03, ..., 4.00000000e+00, 0.00000000e+00, 3.00000000e+00]])

In [ ]:
# No missing values found
np.isnan(loan_data).sum()

0

In [ ]:
header_full = np.concatenate((checkpoint_numeric['header'], checkpoint_strings['header']))
header_full

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate', 'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate', 'issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'addr_state'], dtype='<U19')

**Sorting new dataset**

In [ ]:
loan_data

array([[4.80102260e+07, 3.50000000e+04, 3.19333006e+04, ..., 1.30000000e+01, 1.00000000e+00, 1.00000000e+00],
       [5.76932610e+07, 3.00000000e+04, 2.71324600e+04, ..., 5.00000000e+00, 1.00000000e+00, 4.00000000e+00],
       [5.94327260e+07, 1.50000000e+04, 1.33262996e+04, ..., 1.00000000e+01, 1.00000000e+00, 4.00000000e+00],
       ...,
       [5.04159900e+07, 1.00000000e+04, 8.91029982e+03, ..., 5.00000000e+00, 1.00000000e+00, 1.00000000e+00],
       [4.61541510e+07, 3.50000000e+04, 3.14908999e+04, ..., 1.70000000e+01, 1.00000000e+00, 3.00000000e+00],
       [6.60552490e+07, 1.00000000e+04, 9.14579974e+03, ..., 4.00000000e+00, 0.00000000e+00, 3.00000000e+00]])

In [ ]:
# Sorting data based on ID
np.sort(loan_data[:,0])

array([  373332.,   575239.,   707689., ..., 68614880., 68615915., 68616519.])

In [ ]:
# Adding np.argsort - shows indexes which sort id col
np.argsort(loan_data[:,0])

array([2086, 4812, 2353, ..., 4935, 9388, 8415])

In [ ]:
# passing indexes to original array - Now dtaa is sorted
loan_data = loan_data[np.argsort(loan_data[:,0])]
loan_data

array([[3.73332000e+05, 9.95000000e+03, 9.03808281e+03, ..., 2.10000000e+01, 0.00000000e+00, 1.00000000e+00],
       [5.75239000e+05, 1.20000000e+04, 1.09002004e+04, ..., 2.50000000e+01, 1.00000000e+00, 2.00000000e+00],
       [7.07689000e+05, 1.00000000e+04, 8.92429980e+03, ..., 1.30000000e+01, 1.00000000e+00, 0.00000000e+00],
       ...,
       [6.86148800e+07, 5.60000000e+03, 5.12164785e+03, ..., 8.00000000e+00, 1.00000000e+00, 1.00000000e+00],
       [6.86159150e+07, 4.00000000e+03, 3.65831989e+03, ..., 1.00000000e+01, 1.00000000e+00, 2.00000000e+00],
       [6.86165190e+07, 2.16000000e+04, 1.97549274e+04, ..., 3.00000000e+00, 0.00000000e+00, 2.00000000e+00]])

In [ ]:
# All values are sorted, test by using indexes
np.argsort(loan_data[:,0])

array([   0,    1,    2, ..., 9997, 9998, 9999])

**Storing new dataset**

In [ ]:
# Stack header on top of the loan_data array.
loan_data = np.vstack((header_full, loan_data))
# First one in parameter will come first so we gave header_full before loan_data.
# Observe all numbers automatically converted to text.

In [ ]:
loan_data

array([['id', 'loan_amnt_USD', 'loan_amnt_EUR', ..., 'sub_grade', 'verification_status', 'addr_state'],
       ['373332.0', '9950.0', '9038.082814338286', ..., '21.0', '0.0', '1.0'],
       ['575239.0', '12000.0', '10900.20037910145', ..., '25.0', '1.0', '2.0'],
       ...,
       ['68614880.0', '5600.0', '5121.647851612413', ..., '8.0', '1.0', '1.0'],
       ['68615915.0', '4000.0', '3658.319894008867', ..., '10.0', '1.0', '2.0'],
       ['68616519.0', '21600.0', '19754.927427647883', ..., '3.0', '0.0', '2.0']], dtype='<U32')

**Save the data**

In [ ]:
np.savetxt("loan_data_preprocessed.csv",
           loan_data,
           fmt = '%s',
           delimiter = ',')